
stages:

  # ingest:
  #   cmd: python src/data/ingestion.py

  #   deps:
  #     - src/data/ingestion.py
  #     - data/source/transactions.csv

  #   outs:
  #     - data/raw/transactions.csv

  preprocess:
    cmd: python src/data/preprocessing.py

    deps:
      - src/data/preprocessing.py
      - data/raw/transactions.csv

    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - data/processed/scaler.pkl

  validate:
    cmd: python src/data/validation.py

    deps:
      - src/data/validation.py
      - data/raw/transactions.csv
