stages:

  ingest:
    cmd: python src/data/ingestion.py
    deps:
      - src/data/ingestion.py
      - data/raw/transactions.csv
    outs:
      - data/processed/raw_ingested.csv

  preprocess:
    cmd: python src/data/preprocessing.py
    deps:
      - src/data/preprocessing.py
      - data/processed/raw_ingested.csv
    outs:
      - data/processed/processed_transactions.parquet

  validate:
    cmd: python src/data/validation.py
    deps:
      - src/data/validation.py
      - data/processed/processed_transactions.parquet