apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops
type: Opaque
stringData:
  MLFLOW_TRACKING_URI: "http://mlflow.argo.svc.cluster.local:5000"

  AWS_ACCESS_KEY_ID: "CHANGE_ME"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME"

  MLFLOW_S3_ENDPOINT_URL: "http://minio.argo.svc.cluster.local:9000"

  AWS_DEFAULT_REGION: "us-east-1"