apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mlops-workflow-role
  namespace: mlops

rules:
  # Argo WorkflowTaskResults
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

  # Argo WorkflowTaskSets
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Workflows
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - list
      - watch
      - update
      - patch

  # Pods
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Pod logs
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlops-workflow-rolebinding
  namespace: mlops

subjects:
  - kind: ServiceAccount
    name: mlops-workflow
    namespace: mlops

roleRef:
  kind: Role
  name: mlops-workflow-role
  apiGroup: rbac.authorization.k8s.io